[workspace.one]
description = "My first Workspace"

[[workspace.one.requests]]
name = "Get Request 1"
method = "GET"
url = "https://example.com/api/1"

[workspace.personal]
description = "Workspace for personal API project"

[[workspace.personal.requests]]
name = "Get Request 1"
method = "GET"
url = "https://example.com/api/1"

[[workspace.personal.requests]]
name = "Get users"
method = "GET"
url = "https://example.com/api/users"
